version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: '@types/*'
        update-types: ['version-update:semver-major']
  - package-ecosystem: 'elm'
    directory: '/elm-example/'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: '/elm-example/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: '@types/*'
        update-types: ['version-update:semver-major']
